---
version: "3.8"

services:

  elasticsearch:
    container_name: "elasticsearch"
    image: "elasticsearch:7.8.0"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic-net 
    volumes:
      - type: volume
        source: elastic-data
        target: /usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
  
  kibana:
    container_name: "kibana"
    image: "kibana:7.8.0"
    ports:
      - 5601:5601
    networks:
      - elastic-net
    depends_on:
      - elasticsearch

  logstash:
    container_name: "logstash"
    image: "configured-logstash:7.8.0"
    build: ./logstash
    ports:
      - 5044:5044
      - 9600:9600
      - 9700:9700
    networks:
      - elastic-net
    depends_on:
      - elasticsearch

networks: 
  elastic-net:

volumes:
  elastic-data:
