---
version: "3.8"

services:

  logstash:
    container_name: "logstash-ingest"
    image: "ingest-logstash:7.8.0"
    build: "./build"
    ports:
      - 5000:5000
    volumes:
      - "<host-path>:/data"
